import { JournalEntryKind } from '@core/domain/enums';
import { createUlid } from '@core/application/ulid';
import { PRODUCT_CALENDAR_TIME_ZONE } from '@core/application/utils/calendar';
import type {
  CreateJournalEntryData,
  IJournalAutomationUserQuery,
  IJournalRepository,
} from '@core/application/ports/out/journal-repository.port';
import type { ReviewContextBuilder } from '../review-context.builder';
import type { JournalPreferences, PreferencesService } from '../preferences.service';

export class ReviewAutomationService {
  constructor(
    private readonly journalRepository: IJournalRepository,
    private readonly automationUsers: IJournalAutomationUserQuery,
    private readonly reviewContextBuilder: ReviewContextBuilder,
    private readonly preferencesService: PreferencesService,
  ) {}

  async ensureReviews(userId: string, now = new Date(), timezone?: string | null): Promise<void> {
    await this.ensureDailyReview(userId, now, timezone);
    await this.ensureWeeklyReview(userId, now, timezone);
  }

  async ensureDailyReview(userId: string, now = new Date(), timezone?: string | null): Promise<void> {
    const reviewTimezone = await this.resolveTimezone(userId, timezone);
    const date = addDays(localDateKey(now, reviewTimezone), -1);
    const entryDate = dateOnly(date);
    const contextId = `DAILY:${date}`;
    const existing = await this.journalRepository.list(userId, {
      kind: JournalEntryKind.DAILY_REVIEW,
      contextType: 'AUTO_GENERATED_REVIEW',
      contextId,
      includeDeleted: true,
    });
    if (existing.length > 0) return;

    const context = await this.reviewContextBuilder.build(
      userId,
      { kind: 'DAILY', startDate: date, endDate: date, timezone: reviewTimezone },
      {},
    );
    await this.createOnce(userId, contextId, {
      id: createUlid(),
      kind: JournalEntryKind.DAILY_REVIEW,
      title: `Daily Review — ${date} (Auto-generated)`,
      entryDate,
      timezone: reviewTimezone,
      contextType: 'AUTO_GENERATED_REVIEW',
      contextId,
      contextData: { autoGenerated: true },
      dailyReview: {
        periodDate: entryDate,
        summarySnapshot: context.metrics,
        wentWellMarkdown: '',
        frictionMarkdown: '',
        learnedMarkdown: '',
        contextMarkdown: '',
      },
    });
  }

  async ensureWeeklyReview(userId: string, now = new Date(), timezone?: string | null): Promise<void> {
    const preferences = await this.preferencesService.getPreferences(userId);
    if (!preferences.journal.autoCreateWeeklyReview) return;

    const reviewTimezone = await this.resolveTimezone(userId, timezone);
    const { start, end } = previousWeek(localDateKey(now, reviewTimezone), preferences.journal.weekStartDay);
    const contextId = `WEEKLY:${start}:${end}`;
    const existing = await this.journalRepository.list(userId, {
      kind: JournalEntryKind.WEEKLY_REVIEW,
      contextType: 'AUTO_GENERATED_REVIEW',
      contextId,
      includeDeleted: true,
    });
    if (existing.length > 0) return;

    const context = await this.reviewContextBuilder.build(
      userId,
      { kind: 'WEEKLY', startDate: start, endDate: end, timezone: reviewTimezone },
      {},
    );
    await this.createOnce(userId, contextId, {
      id: createUlid(),
      kind: JournalEntryKind.WEEKLY_REVIEW,
      title: `Weekly Review — ${start} to ${end} (Auto-generated)`,
      entryDate: dateOnly(start),
      timezone: reviewTimezone,
      contextType: 'AUTO_GENERATED_REVIEW',
      contextId,
      contextData: { autoGenerated: true },
      weeklyReview: {
        periodStart: dateOnly(start),
        periodEnd: dateOnly(end),
        summarySnapshot: context.metrics,
        comparisonSnapshot: context.previousPeriod?.comparison,
        wentWellMarkdown: '',
        frictionMarkdown: '',
        learnedMarkdown: '',
        differentFromLastWeekMarkdown: '',
        nextWeekMarkdown: '',
        experimentSnapshot: { hypothesis: '', action: '', success: '' },
      },
    });
  }

  private async createOnce(userId: string, contextId: string, data: CreateJournalEntryData): Promise<void> {
    try {
      await this.journalRepository.create(userId, data);
    } catch (error) {
      if (!isUniqueViolation(error)) throw error;
      const existing = await this.journalRepository.list(userId, {
        contextType: 'AUTO_GENERATED_REVIEW',
        contextId,
        includeDeleted: true,
      });
      if (existing.length === 0) throw error;
    }
  }

  private async resolveTimezone(userId: string, requested?: string | null): Promise<string> {
    const candidate = requested ?? (await this.automationUsers.findTimezone(userId));
    return isValidTimezone(candidate) ? candidate : PRODUCT_CALENDAR_TIME_ZONE;
  }
}

export function previousWeek(today: string, weekStartDay: JournalPreferences['weekStartDay']): { start: string; end: string } {
  const weekday = new Date(`${today}T00:00:00Z`).getUTCDay();
  const daysSinceStart = weekStartDay === 'SUNDAY' ? weekday : (weekday + 6) % 7;
  const end = addDays(today, -daysSinceStart - 1);
  return { start: addDays(end, -6), end };
}

function localDateKey(value: Date, timezone: string): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: timezone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(value);
  const fields = Object.fromEntries(parts.map(({ type, value: part }) => [type, part]));
  return `${fields.year}-${fields.month}-${fields.day}`;
}

function addDays(date: string, days: number): string {
  const value = new Date(`${date}T00:00:00Z`);
  value.setUTCDate(value.getUTCDate() + days);
  return value.toISOString().slice(0, 10);
}

function dateOnly(date: string): Date {
  return new Date(`${date}T00:00:00Z`);
}

function isValidTimezone(value: string | null | undefined): value is string {
  if (!value) return false;
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: value }).format();
    return true;
  } catch {
    return false;
  }
}

function isUniqueViolation(error: unknown): boolean {
  return Boolean(error && typeof error === 'object' && 'code' in error && error.code === 'P2002');
}
