import { JournalEntryKind } from '@core/domain/enums';
import { ReviewAutomationService } from './review-automation.service';

describe('ReviewAutomationService', () => {
  let service: ReviewAutomationService;
  let journal: any;
  let users: any;
  let contextBuilder: any;
  let preferences: any;

  beforeEach(() => {
    journal = { list: jest.fn().mockResolvedValue([]), create: jest.fn().mockResolvedValue({}) };
    users = { findTimezone: jest.fn().mockResolvedValue('Asia/Ho_Chi_Minh') };
    contextBuilder = {
      build: jest.fn().mockResolvedValue({
        metrics: { tasks: { completed: 3 } },
        previousPeriod: { comparison: { 'tasks.completed': { current: 3, previous: 1 } } },
      }),
    };
    preferences = {
      getPreferences: jest.fn().mockResolvedValue({ journal: { autoCreateWeeklyReview: true, weekStartDay: 'MONDAY' } }),
    };
    service = new ReviewAutomationService(journal, users, contextBuilder, preferences);
  });

  it('creates the previous day with metrics and empty answers', async () => {
    await service.ensureDailyReview('user1', new Date('2026-08-20T12:00:00Z'));

    expect(journal.create).toHaveBeenCalledWith(
      'user1',
      expect.objectContaining({
        kind: JournalEntryKind.DAILY_REVIEW,
        title: 'Daily Review — 2026-08-19 (Auto-generated)',
        timezone: 'Asia/Ho_Chi_Minh',
        contextData: { autoGenerated: true },
        dailyReview: expect.objectContaining({
          summarySnapshot: { tasks: { completed: 3 } },
          wentWellMarkdown: '',
          frictionMarkdown: '',
          learnedMarkdown: '',
          contextMarkdown: '',
        }),
      }),
    );
  });

  it('uses the configured week start and leaves weekly answers empty', async () => {
    await service.ensureWeeklyReview('user1', new Date('2026-08-20T12:00:00Z'));

    expect(journal.create).toHaveBeenCalledWith(
      'user1',
      expect.objectContaining({
        kind: JournalEntryKind.WEEKLY_REVIEW,
        title: 'Weekly Review — 2026-08-10 to 2026-08-16 (Auto-generated)',
        weeklyReview: expect.objectContaining({
          summarySnapshot: { tasks: { completed: 3 } },
          wentWellMarkdown: '',
          frictionMarkdown: '',
          learnedMarkdown: '',
          differentFromLastWeekMarkdown: '',
          nextWeekMarkdown: '',
        }),
      }),
    );
  });

  it('uses a stored user timezone for period boundaries', async () => {
    users.findTimezone.mockResolvedValue('America/Los_Angeles');

    await service.ensureDailyReview('user1', new Date('2026-08-20T06:30:00Z'));

    expect(contextBuilder.build).toHaveBeenCalledWith(
      'user1',
      expect.objectContaining({ startDate: '2026-08-18', endDate: '2026-08-18', timezone: 'America/Los_Angeles' }),
      {},
    );
  });

  it('does not create a disabled weekly review', async () => {
    preferences.getPreferences.mockResolvedValue({ journal: { autoCreateWeeklyReview: false, weekStartDay: 'MONDAY' } });

    await service.ensureWeeklyReview('user1', new Date('2026-08-20T12:00:00Z'));

    expect(journal.create).not.toHaveBeenCalled();
  });

  it('treats a concurrent unique-key race as already generated', async () => {
    journal.create.mockRejectedValue({ code: 'P2002' });
    journal.list.mockResolvedValueOnce([]).mockResolvedValueOnce([{ id: 'winner' }]);

    await expect(service.ensureDailyReview('user1', new Date('2026-08-20T12:00:00Z'))).resolves.toBeUndefined();
    expect(journal.list).toHaveBeenCalledTimes(2);
  });
});
