import Foundation

public enum iTuCalendarSupport {
    public static let timezone = TimeZone(identifier: "Asia/Ho_Chi_Minh")!
    public static func calendar(firstWeekday: Int? = nil) -> Calendar { var calendar = Calendar(identifier: .gregorian); calendar.timeZone = timezone; if let firstWeekday { calendar.firstWeekday = firstWeekday }; return calendar }
    public static func dayString(_ date: Date = Date()) -> String { let components = calendar().dateComponents([.year, .month, .day], from: date); return String(format: "%04d-%02d-%02d", components.year ?? 0, components.month ?? 0, components.day ?? 0) }
    public static func monthString(_ date: Date = Date()) -> String { let components = calendar().dateComponents([.year, .month], from: date); return String(format: "%04d-%02d", components.year ?? 0, components.month ?? 0) }
    public static func weekRange(containing date: Date = Date(), weekStartDay: String) -> (start: String, end: String) { let cal = calendar(firstWeekday: weekStartDay.uppercased() == "SUNDAY" ? 1 : 2); let day = cal.startOfDay(for: date); let weekday = cal.component(.weekday, from: day); let offset = (weekday - cal.firstWeekday + 7) % 7; let start = cal.date(byAdding: .day, value: -offset, to: day) ?? day; let end = cal.date(byAdding: .day, value: 6, to: start) ?? start; return (dayString(start), dayString(end)) }
}

public struct JournalNoteModel: Codable, Sendable, Identifiable, Equatable {
    public let id: String; public let userId: String; public let kind: String; public var title: String; public var contentMarkdown: String; public var entryDate: String; public var timezone: String; public var templateId: String?; public var tagIds: [String]; public var version: Int; public let createdAt: String; public var updatedAt: String; public var deletedAt: String?; public var deletedByDeviceId: String?; public var weeklyReview: JournalWeeklyReviewModel?; public var dailyReview: JournalDailyReviewModel?; public var tags: [JournalTagModel]; public var attachments: [JournalAttachmentModel]; public var contextType: String?; public var contextId: String?; public var contextData: JSONValue?
    public init(id: String, userId: String, kind: String = "NOTE", title: String, contentMarkdown: String, entryDate: String, updatedAt: String, timezone: String = iTuCalendarSupport.timezone.identifier, templateId: String? = nil, tagIds: [String] = [], version: Int = 1, createdAt: String? = nil, deletedAt: String? = nil, deletedByDeviceId: String? = nil, weeklyReview: JournalWeeklyReviewModel? = nil, dailyReview: JournalDailyReviewModel? = nil, tags: [JournalTagModel] = [], attachments: [JournalAttachmentModel] = [], contextType: String? = nil, contextId: String? = nil, contextData: JSONValue? = nil) { self.id = id; self.userId = userId; self.kind = kind; self.title = title; self.contentMarkdown = contentMarkdown; self.entryDate = entryDate; self.timezone = timezone; self.templateId = templateId; self.tagIds = tagIds; self.version = version; self.createdAt = createdAt ?? updatedAt; self.updatedAt = updatedAt; self.deletedAt = deletedAt; self.deletedByDeviceId = deletedByDeviceId; self.weeklyReview = weeklyReview; self.dailyReview = dailyReview; self.tags = tags; self.attachments = attachments; self.contextType = contextType; self.contextId = contextId; self.contextData = contextData }
    public var previewText: String { let plainText = contentMarkdown.replacingOccurrences(of: "#", with: "").replacingOccurrences(of: "*", with: "").replacingOccurrences(of: "`", with: "").replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespacesAndNewlines); return plainText.isEmpty ? "An empty page, ready for the next line." : plainText }
    public var displayDate: String { String(entryDate.prefix(10)) }
    private enum CodingKeys: String, CodingKey { case id, userId, kind, title, contentMarkdown, entryDate, timezone, templateId, tagIds, version, createdAt, updatedAt, deletedAt, deletedByDeviceId, weeklyReview, dailyReview, tags, attachments, contextType, contextId, contextData }
    public init(from decoder: Decoder) throws { let values = try decoder.container(keyedBy: CodingKeys.self); id = try values.decode(String.self, forKey: .id); userId = try values.decodeIfPresent(String.self, forKey: .userId) ?? "local"; kind = try values.decodeIfPresent(String.self, forKey: .kind) ?? "NOTE"; title = try values.decodeIfPresent(String.self, forKey: .title) ?? ""; contentMarkdown = try values.decodeIfPresent(String.self, forKey: .contentMarkdown) ?? ""; entryDate = try values.decodeIfPresent(String.self, forKey: .entryDate) ?? ""; timezone = try values.decodeIfPresent(String.self, forKey: .timezone) ?? iTuCalendarSupport.timezone.identifier; templateId = try values.decodeIfPresent(String.self, forKey: .templateId); tagIds = try values.decodeIfPresent([String].self, forKey: .tagIds) ?? []; version = try values.decodeIfPresent(Int.self, forKey: .version) ?? 1; createdAt = try values.decodeIfPresent(String.self, forKey: .createdAt) ?? ""; updatedAt = try values.decodeIfPresent(String.self, forKey: .updatedAt) ?? createdAt; deletedAt = try values.decodeIfPresent(String.self, forKey: .deletedAt); deletedByDeviceId = try values.decodeIfPresent(String.self, forKey: .deletedByDeviceId); weeklyReview = try values.decodeIfPresent(JournalWeeklyReviewModel.self, forKey: .weeklyReview); dailyReview = try values.decodeIfPresent(JournalDailyReviewModel.self, forKey: .dailyReview); tags = try values.decodeIfPresent([JournalTagModel].self, forKey: .tags) ?? []; attachments = try values.decodeIfPresent([JournalAttachmentModel].self, forKey: .attachments) ?? []; contextType = try values.decodeIfPresent(String.self, forKey: .contextType); contextId = try values.decodeIfPresent(String.self, forKey: .contextId); contextData = try values.decodeIfPresent(JSONValue.self, forKey: .contextData) }
}

public struct JournalWeeklyReviewModel: Codable, Sendable, Equatable {
    public let entryId: String; public var periodStart: String; public var periodEnd: String; public var summarySnapshot: [String: JSONValue]; public var wentWellMarkdown: String?; public var frictionMarkdown: String?; public var learnedMarkdown: String?; public var differentFromLastWeekMarkdown: String?; public var nextWeekMarkdown: String?; public var experimentSnapshot: JSONValue?; public var comparisonSnapshot: JSONValue?; public var aiInsightsSnapshot: JSONValue?; public var aiGenerationJobId: String?; public var aiGeneratedAt: String?; public var aiPromptVersion: String?; public var aiSourceEntryVersion: Int?
    public init(entryId: String, periodStart: String, periodEnd: String, summarySnapshot: [String: JSONValue], wentWellMarkdown: String? = nil, frictionMarkdown: String? = nil, learnedMarkdown: String? = nil, differentFromLastWeekMarkdown: String? = nil, nextWeekMarkdown: String? = nil, experimentSnapshot: JSONValue? = nil, comparisonSnapshot: JSONValue? = nil, aiInsightsSnapshot: JSONValue? = nil, aiGenerationJobId: String? = nil, aiGeneratedAt: String? = nil, aiPromptVersion: String? = nil, aiSourceEntryVersion: Int? = nil) { self.entryId = entryId; self.periodStart = periodStart; self.periodEnd = periodEnd; self.summarySnapshot = summarySnapshot; self.wentWellMarkdown = wentWellMarkdown; self.frictionMarkdown = frictionMarkdown; self.learnedMarkdown = learnedMarkdown; self.differentFromLastWeekMarkdown = differentFromLastWeekMarkdown; self.nextWeekMarkdown = nextWeekMarkdown; self.experimentSnapshot = experimentSnapshot; self.comparisonSnapshot = comparisonSnapshot; self.aiInsightsSnapshot = aiInsightsSnapshot; self.aiGenerationJobId = aiGenerationJobId; self.aiGeneratedAt = aiGeneratedAt; self.aiPromptVersion = aiPromptVersion; self.aiSourceEntryVersion = aiSourceEntryVersion }
}

public struct JournalDailyReviewModel: Codable, Sendable, Equatable {
    public let entryId: String; public var periodDate: String; public var summarySnapshot: [String: JSONValue]; public var wentWellMarkdown: String?; public var frictionMarkdown: String?; public var learnedMarkdown: String?; public var contextMarkdown: String?; public var aiInsightsSnapshot: JSONValue?; public var aiGenerationJobId: String?; public var aiGeneratedAt: String?; public var aiPromptVersion: String?; public var aiSourceEntryVersion: Int?
    public init(entryId: String, periodDate: String, summarySnapshot: [String: JSONValue], wentWellMarkdown: String? = nil, frictionMarkdown: String? = nil, learnedMarkdown: String? = nil, contextMarkdown: String? = nil, aiInsightsSnapshot: JSONValue? = nil, aiGenerationJobId: String? = nil, aiGeneratedAt: String? = nil, aiPromptVersion: String? = nil, aiSourceEntryVersion: Int? = nil) { self.entryId = entryId; self.periodDate = periodDate; self.summarySnapshot = summarySnapshot; self.wentWellMarkdown = wentWellMarkdown; self.frictionMarkdown = frictionMarkdown; self.learnedMarkdown = learnedMarkdown; self.contextMarkdown = contextMarkdown; self.aiInsightsSnapshot = aiInsightsSnapshot; self.aiGenerationJobId = aiGenerationJobId; self.aiGeneratedAt = aiGeneratedAt; self.aiPromptVersion = aiPromptVersion; self.aiSourceEntryVersion = aiSourceEntryVersion }
}

public struct JournalTagModel: Codable, Sendable, Equatable, Identifiable {
    public let id: String; public let userId: String; public var name: String; public var color: String; public let createdAt: String; public var updatedAt: String
    public init(id: String, userId: String, name: String, color: String, createdAt: String, updatedAt: String) { self.id = id; self.userId = userId; self.name = name; self.color = color; self.createdAt = createdAt; self.updatedAt = updatedAt }
}

public struct JournalAttachmentModel: Codable, Sendable, Equatable, Identifiable {
    public let id: String; public let userId: String; public let entryId: String; public var fileName: String; public var mimeType: String; public var sizeBytes: Int; public var storageKey: String; public var url: String?; public let createdAt: String; public var deletedAt: String?
    public init(id: String, userId: String, entryId: String, fileName: String, mimeType: String, sizeBytes: Int, storageKey: String, url: String?, createdAt: String, deletedAt: String?) { self.id = id; self.userId = userId; self.entryId = entryId; self.fileName = fileName; self.mimeType = mimeType; self.sizeBytes = sizeBytes; self.storageKey = storageKey; self.url = url; self.createdAt = createdAt; self.deletedAt = deletedAt }
}

public struct JournalEntryRevisionModel: Codable, Sendable, Equatable, Identifiable {
    public let id: String; public let entryId: String; public let revisionNumber: Int; public let snapshot: [String: JSONValue]; public let mutationId: String?; public let deviceId: String?; public let createdAt: String
    public init(id: String, entryId: String, revisionNumber: Int, snapshot: [String: JSONValue], mutationId: String?, deviceId: String?, createdAt: String) { self.id = id; self.entryId = entryId; self.revisionNumber = revisionNumber; self.snapshot = snapshot; self.mutationId = mutationId; self.deviceId = deviceId; self.createdAt = createdAt }
}

public struct JournalTemplateModel: Codable, Sendable, Equatable, Identifiable {
    public let id: String; public let userId: String; public var name: String; public var entryKind: String; public var titleTemplate: String; public var bodyMarkdown: String; public var defaults: [String: JSONValue]; public var builtIn: Bool; public var archivedAt: String?; public var version: Int; public let createdAt: String; public var updatedAt: String
    public init(id: String, userId: String, name: String, entryKind: String, titleTemplate: String, bodyMarkdown: String, defaults: [String: JSONValue], builtIn: Bool, archivedAt: String?, version: Int, createdAt: String, updatedAt: String) { self.id = id; self.userId = userId; self.name = name; self.entryKind = entryKind; self.titleTemplate = titleTemplate; self.bodyMarkdown = bodyMarkdown; self.defaults = defaults; self.builtIn = builtIn; self.archivedAt = archivedAt; self.version = version; self.createdAt = createdAt; self.updatedAt = updatedAt }
}

public struct JournalPreferencesModel: Codable, Sendable, Equatable {
    public var defaultEditorMode: String; public var autoCreateDailyNote: Bool; public var autoOpenTodayNote: Bool; public var weekStartDay: String; public var autoCreateWeeklyReview: Bool
    public init(defaultEditorMode: String = "LIVE", autoCreateDailyNote: Bool = true, autoOpenTodayNote: Bool = true, weekStartDay: String = "MONDAY", autoCreateWeeklyReview: Bool = true) { self.defaultEditorMode = defaultEditorMode; self.autoCreateDailyNote = autoCreateDailyNote; self.autoOpenTodayNote = autoOpenTodayNote; self.weekStartDay = weekStartDay; self.autoCreateWeeklyReview = autoCreateWeeklyReview }
}

public struct JournalPendingAttachment: Codable, Sendable, Equatable {
    public let entryId: String; public let fileName: String; public let mimeType: String
    public init(entryId: String, fileName: String, mimeType: String) { self.entryId = entryId; self.fileName = fileName; self.mimeType = mimeType }
}
