import Foundation

public struct DeckModel: Identifiable, Codable, Equatable, Sendable {
    public let id: String; public var title: String; public var description: String; public var cardCount: Int; public var dueCount: Int; public var color: String; public var icon: String; public var lastReviewedAt: String?; public var version: Int
    private enum CodingKeys: String, CodingKey { case id, title, description, cardCount, dueCount, color, icon, lastReviewedAt, version, isDefault, archived, studyStats }
    public init(id: String, title: String, description: String, cardCount: Int, dueCount: Int, color: String, icon: String, lastReviewedAt: String? = nil, version: Int = 1) { self.id = id; self.title = title; self.description = description; self.cardCount = cardCount; self.dueCount = dueCount; self.color = color; self.icon = icon; self.lastReviewedAt = lastReviewedAt; self.version = version }
    public init(from decoder: Decoder) throws { let values = try decoder.container(keyedBy: CodingKeys.self); id = try values.decode(String.self, forKey: .id); title = try values.decodeIfPresent(String.self, forKey: .title) ?? "Untitled deck"; description = try values.decodeIfPresent(String.self, forKey: .description) ?? ""; cardCount = try values.decodeIfPresent(Int.self, forKey: .cardCount) ?? 0; dueCount = try values.decodeIfPresent(Int.self, forKey: .dueCount) ?? 0; if let stats = try values.decodeIfPresent(DeckStudyStats.self, forKey: .studyStats) { cardCount = stats.totalCards ?? cardCount; dueCount = stats.dueCount ?? dueCount; lastReviewedAt = stats.lastStudiedAt } else { lastReviewedAt = try values.decodeIfPresent(String.self, forKey: .lastReviewedAt) }; let serverIcon = try values.decodeIfPresent(String.self, forKey: .icon) ?? "BOOK"; icon = Self.sfSymbol(forServerIcon: serverIcon); color = (try values.decodeIfPresent(String.self, forKey: .color) ?? "teal").lowercased(); version = try values.decodeIfPresent(Int.self, forKey: .version) ?? 1 }
    public func encode(to encoder: Encoder) throws { var values = encoder.container(keyedBy: CodingKeys.self); try values.encode(id, forKey: .id); try values.encode(title, forKey: .title); try values.encode(description, forKey: .description); try values.encode(cardCount, forKey: .cardCount); try values.encode(dueCount, forKey: .dueCount); try values.encode(color, forKey: .color); try values.encode(icon, forKey: .icon); try values.encodeIfPresent(lastReviewedAt, forKey: .lastReviewedAt); try values.encode(version, forKey: .version) }
    private struct DeckStudyStats: Decodable { let totalCards: Int?; let dueCount: Int?; let lastStudiedAt: String? }
    private static func sfSymbol(forServerIcon icon: String) -> String { switch icon.uppercased() { case "INBOX": return "tray"; case "BRAIN": return "brain"; case "LANGUAGE": return "character.book.closed"; case "FLASK": return "flask"; case "CODE": return "chevron.left.forwardslash.chevron.right"; case "LEAF": return "leaf"; case "CALCULATOR": return "function"; case "GLOBE": return "globe"; default: return icon.contains(".") ? icon : "book.closed" } }
    public static func sampleDecks() -> [DeckModel] { [DeckModel(id: "deck-1", title: "Swift & SwiftUI Mastery", description: "Design patterns, view lifecycle, and state management", cardCount: 24, dueCount: 8, color: "teal", icon: "swift"), DeckModel(id: "deck-2", title: "System Architecture", description: "Clean Architecture, Hexagonal patterns, and CQRS", cardCount: 16, dueCount: 3, color: "mint", icon: "server.rack"), DeckModel(id: "deck-3", title: "Productivity Principles", description: "Timeblocking, Eisenhower matrix, and Spaced Repetition", cardCount: 12, dueCount: 0, color: "amber", icon: "brain")] }
}

public struct CardModel: Identifiable, Codable, Equatable, Sendable {
    public let id: String; public let deckId: String; public var type: String; public var frontMarkdown: String; public var backMarkdown: String; public var tags: [String]; public var state: String; public var intervalDays: Int; public var easeFactor: Double; public var reviewDirection: String; public var version: Int
    private enum CodingKeys: String, CodingKey { case id, deckId, type, frontMarkdown, backMarkdown, promptRichText, answerRichText, tags, state, intervalDays, easeFactor, reviewDirection, version }
    public init(id: String, deckId: String, frontMarkdown: String, backMarkdown: String, state: String, intervalDays: Int, easeFactor: Double, reviewDirection: String = "FRONT_TO_BACK", type: String = "BASIC", tags: [String] = [], version: Int = 1) { self.id = id; self.deckId = deckId; self.type = type; self.frontMarkdown = frontMarkdown; self.backMarkdown = backMarkdown; self.tags = tags; self.state = state; self.intervalDays = intervalDays; self.easeFactor = easeFactor; self.reviewDirection = reviewDirection; self.version = version }
    public init(from decoder: Decoder) throws { let values = try decoder.container(keyedBy: CodingKeys.self); id = try values.decode(String.self, forKey: .id); deckId = try values.decode(String.self, forKey: .deckId); type = try values.decodeIfPresent(String.self, forKey: .type) ?? "BASIC"; let decodedFront = try values.decodeIfPresent(String.self, forKey: .frontMarkdown); let prompt = try values.decodeIfPresent(String.self, forKey: .promptRichText); frontMarkdown = decodedFront ?? prompt ?? ""; let decodedBack = try values.decodeIfPresent(String.self, forKey: .backMarkdown); let answer = try values.decodeIfPresent(String.self, forKey: .answerRichText); backMarkdown = decodedBack ?? answer ?? ""; tags = try values.decodeIfPresent([String].self, forKey: .tags) ?? []; state = try values.decodeIfPresent(String.self, forKey: .state) ?? "new"; intervalDays = try values.decodeIfPresent(Int.self, forKey: .intervalDays) ?? 0; easeFactor = try values.decodeIfPresent(Double.self, forKey: .easeFactor) ?? 2.5; reviewDirection = try values.decodeIfPresent(String.self, forKey: .reviewDirection) ?? "FRONT_TO_BACK"; version = try values.decodeIfPresent(Int.self, forKey: .version) ?? 1 }
    public func encode(to encoder: Encoder) throws { var values = encoder.container(keyedBy: CodingKeys.self); try values.encode(id, forKey: .id); try values.encode(deckId, forKey: .deckId); try values.encode(type, forKey: .type); try values.encode(frontMarkdown, forKey: .frontMarkdown); try values.encode(backMarkdown, forKey: .backMarkdown); try values.encode(tags, forKey: .tags); try values.encode(state, forKey: .state); try values.encode(intervalDays, forKey: .intervalDays); try values.encode(easeFactor, forKey: .easeFactor); try values.encode(reviewDirection, forKey: .reviewDirection); try values.encode(version, forKey: .version) }
    public static func sampleCards(deckId: String) -> [CardModel] { [CardModel(id: "card-1", deckId: deckId, frontMarkdown: "What is `@Observable` in Swift 5.9+?", backMarkdown: "Macro that replaces `ObservableObject` and `Published`, providing fine-grained tracking per property.", state: "review", intervalDays: 3, easeFactor: 2.5), CardModel(id: "card-2", deckId: deckId, frontMarkdown: "What is the purpose of Hexagonal Architecture?", backMarkdown: "Isolate core domain business logic from external frameworks, databases, and UI transport layers via ports and adapters.", state: "learning", intervalDays: 1, easeFactor: 2.3), CardModel(id: "card-3", deckId: deckId, frontMarkdown: "Explain the Spaced Repetition SM-2 Algorithm principle.", backMarkdown: "Calculates review interval multiplier based on recall quality grades (0 to 5), optimizing long-term memory retention.", state: "new", intervalDays: 0, easeFactor: 2.5)] }
}

public struct StudySessionHistoryItem: Identifiable, Codable, Equatable, Sendable {
    public let id: String; public let deckId: String?; public let deckTitle: String?; public let mode: String; public let rating: Int?; public let reviewed: Int; public let correct: Int; public let correctRate: Int; public let startedAt: String; public let completedAt: String?
    public init(id: String, deckId: String?, deckTitle: String?, mode: String, rating: Int?, reviewed: Int, correct: Int, correctRate: Int, startedAt: String, completedAt: String?) { self.id = id; self.deckId = deckId; self.deckTitle = deckTitle; self.mode = mode; self.rating = rating; self.reviewed = reviewed; self.correct = correct; self.correctRate = correctRate; self.startedAt = startedAt; self.completedAt = completedAt }
}

public struct SessionReviewItem: Codable, Equatable, Sendable {
    public let cardId: String; public let direction: String; public let grade: String; public let userAnswer: String?; public let promptRichText: String; public let answerRichText: String
    public init(cardId: String, direction: String, grade: String, userAnswer: String?, promptRichText: String, answerRichText: String) { self.cardId = cardId; self.direction = direction; self.grade = grade; self.userAnswer = userAnswer; self.promptRichText = promptRichText; self.answerRichText = answerRichText }
}

public struct StudySessionFeedback: Codable, Equatable, Sendable {
    public let summary: String; public let nextSteps: [String]
    public init(summary: String, nextSteps: [String]) { self.summary = summary; self.nextSteps = nextSteps }
}

public struct StudySessionDetails: Codable, Equatable, Sendable {
    public let id: String; public let deckId: String?; public let deckTitle: String?; public let mode: String; public let rating: Int?; public let reviewed: Int; public let correct: Int; public let correctRate: Int; public let startedAt: String; public let completedAt: String?; public let reviews: [SessionReviewItem]; public let feedback: StudySessionFeedback?
    public init(id: String, deckId: String?, deckTitle: String?, mode: String, rating: Int?, reviewed: Int, correct: Int, correctRate: Int, startedAt: String, completedAt: String?, reviews: [SessionReviewItem], feedback: StudySessionFeedback?) { self.id = id; self.deckId = deckId; self.deckTitle = deckTitle; self.mode = mode; self.rating = rating; self.reviewed = reviewed; self.correct = correct; self.correctRate = correctRate; self.startedAt = startedAt; self.completedAt = completedAt; self.reviews = reviews; self.feedback = feedback }
}
