import iTuDomain

typealias HabitFrequency = iTuDomain.HabitFrequency
typealias HabitDirection = iTuDomain.HabitDirection
typealias HabitOccurrenceStatus = iTuDomain.HabitOccurrenceStatus
typealias HabitProjectedStatus = iTuDomain.HabitProjectedStatus
typealias HabitPreferencesModel = iTuDomain.HabitPreferencesModel
typealias HabitDayStateModel = iTuDomain.HabitDayStateModel
typealias HabitCalendarResponse = iTuDomain.HabitCalendarResponse
typealias HabitProgressResultModel = iTuDomain.HabitProgressResultModel
typealias HabitQuickLogRequest = iTuDomain.HabitQuickLogRequest
typealias HabitProgressLogModel = iTuDomain.HabitProgressLogModel
typealias HabitReminderDeliveryModel = iTuDomain.HabitReminderDeliveryModel
typealias HabitChecklistItemModel = iTuDomain.HabitChecklistItemModel
typealias HabitOccurrenceModel = iTuDomain.HabitOccurrenceModel
typealias HabitModel = iTuDomain.HabitModel
typealias HabitTimeBlockModel = iTuDomain.HabitTimeBlockModel
typealias HabitStatsModel = iTuDomain.HabitStatsModel
