import iTuDomain

typealias UsageAppIdentity = iTuDomain.UsageAppIdentity
typealias UsageSummary = iTuDomain.UsageSummary
typealias WebsiteUsageSummary = iTuDomain.WebsiteUsageSummary
typealias UsageUploadWatermark = iTuDomain.UsageUploadWatermark
typealias UsagePreferences = iTuDomain.UsagePreferences
typealias UsageTopApp = iTuDomain.UsageTopApp
typealias UsageDailyTotal = iTuDomain.UsageDailyTotal
typealias UsageDailyApp = iTuDomain.UsageDailyApp
typealias UsageHourlyApp = iTuDomain.UsageHourlyApp
typealias EngagementCoverage = iTuDomain.EngagementCoverage
typealias UsageStatistics = iTuDomain.UsageStatistics
typealias WebsiteUsageHostnameTotal = iTuDomain.WebsiteUsageHostnameTotal
typealias WebsiteUsageDailyTotal = iTuDomain.WebsiteUsageDailyTotal
typealias WebsiteUsageBrowserTotal = iTuDomain.WebsiteUsageBrowserTotal
typealias WebsiteUsageURLDetail = iTuDomain.WebsiteUsageURLDetail
typealias WebsiteUsageSession = iTuDomain.WebsiteUsageSession
typealias WebsiteActivityPrivacyFilter = iTuDomain.WebsiteActivityPrivacyFilter
typealias WebsiteUsageStatistics = iTuDomain.WebsiteUsageStatistics
