import iTuDomain

typealias CalendarTimelineResponse = iTuDomain.CalendarTimelineResponse
typealias CalendarTimelineItem = iTuDomain.CalendarTimelineItem
typealias ExternalCalendarModel = iTuDomain.ExternalCalendarModel
typealias CalendarPreferencesModel = iTuDomain.CalendarPreferencesModel
