import type { CatalogExerciseDefinition } from './gym-exercise-catalog.types';

export const LOWER_BODY_EXERCISES: CatalogExerciseDefinition[] = [
  // LEGS - QUADS
  {
    catalogKey: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 150,
    description: 'Foundational lower body compound squat.',
  },
  {
    catalogKey: 'front-squat',
    name: 'Front Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Abs', 'Upper Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Anterior-loaded squat with upright torso emphasizing quadriceps.',
  },
  {
    catalogKey: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Abs'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Kettlebell or dumbbell held at chest during squatting.',
  },
  {
    catalogKey: 'leg-press',
    name: 'Leg Press',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Incline machine leg press.',
  },
  {
    catalogKey: 'hack-squat',
    name: 'Hack Squat Machine',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Guided sled squat machine allowing deep knee flexion.',
  },
  {
    catalogKey: 'leg-extension',
    name: 'Leg Extension',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated open-chain quadriceps isolation.',
  },
  {
    catalogKey: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Rear-foot-elevated split squat for unilateral leg power.',
  },
  {
    catalogKey: 'walking-lunge',
    name: 'Walking Lunge',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Calves'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Dynamic forward lunging with dumbbells or barbell.',
  },

  // LEGS - HAMSTRINGS
  {
    catalogKey: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Calves'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Prone machine hamstring curl for knee flexion strength.',
  },
  {
    catalogKey: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated hamstring curl loading the hamstrings in a lengthened hip position.',
  },
  {
    catalogKey: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Eccentric hamstring bodyweight curl.',
  },

  // LEGS - GLUTES
  {
    catalogKey: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings', 'Quads'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Bench-supported hip thrust for maximal gluteus maximus contraction.',
  },
  {
    catalogKey: 'cable-glute-kickback',
    name: 'Cable Glute Kickback',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Ankle strap cable kickback isolating glutes.',
  },
  {
    catalogKey: 'machine-hip-abduction',
    name: 'Machine Hip Abduction',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated machine abduction targeting gluteus medius and minimus.',
  },

  // LEGS - CALVES
  {
    catalogKey: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscleGroup: 'Calves',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Standing straight-leg calf raise targeting gastrocnemius.',
  },
  {
    catalogKey: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    primaryMuscleGroup: 'Calves',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Bent-knee seated calf raise isolating the soleus muscle.',
  },

];

