import type { CatalogExerciseDefinition } from './gym-exercise-catalog.types';

export const UPPER_BODY_EXERCISES: CatalogExerciseDefinition[] = [
  // CHEST
  {
    catalogKey: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Flat bench barbell press for chest strength and hypertrophy.',
  },
  {
    catalogKey: 'incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Incline bench press targeting clavicular head of the pectoralis.',
  },
  {
    catalogKey: 'decline-barbell-bench-press',
    name: 'Decline Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Decline bench press targeting lower pectoral fibers.',
  },
  {
    catalogKey: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Flat dumbbell press allowing deep stretch and independent arm control.',
  },
  {
    catalogKey: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline dumbbell press for upper chest development.',
  },
  {
    catalogKey: 'decline-dumbbell-press',
    name: 'Decline Dumbbell Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Decline dumbbell press emphasizing lower pectorals.',
  },
  {
    catalogKey: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Isolation movement focusing on chest stretch and adduction.',
  },
  {
    catalogKey: 'incline-dumbbell-flyes',
    name: 'Incline Dumbbell Flyes',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Incline flyes for upper chest stretch.',
  },
  {
    catalogKey: 'cable-crossover',
    name: 'Cable Crossover',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing cable chest fly providing constant muscular tension.',
  },
  {
    catalogKey: 'low-to-high-cable-fly',
    name: 'Low to High Cable Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Upward cable fly targeting the upper pectorals.',
  },
  {
    catalogKey: 'high-to-low-cable-fly',
    name: 'High to Low Cable Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Downward cable fly targeting the lower chest.',
  },
  {
    catalogKey: 'chest-dip',
    name: 'Chest Dip',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Parallel bar dips with torso leaned forward to recruit chest.',
  },
  {
    catalogKey: 'push-up',
    name: 'Push Up',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts', 'Abs'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standard floor push up.',
  },
  {
    catalogKey: 'diamond-push-up',
    name: 'Diamond Push Up',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Close hand placement push up targeting triceps and inner chest.',
  },
  {
    catalogKey: 'machine-chest-press',
    name: 'Machine Chest Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Guided seated chest press machine.',
  },
  {
    catalogKey: 'incline-machine-chest-press',
    name: 'Incline Machine Chest Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline guided machine press for upper chest.',
  },
  {
    catalogKey: 'pec-deck-fly',
    name: 'Pec Deck Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Machine seated chest fly with steady resistance curve.',
  },

  // BACK / LATS / UPPER BACK
  {
    catalogKey: 'pull-up',
    name: 'Pull Up',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Overhand grip pull up for lat width and vertical pulling strength.',
  },
  {
    catalogKey: 'chin-up',
    name: 'Chin Up',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Underhand grip vertical pull with high bicep involvement.',
  },
  {
    catalogKey: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Wide grip seated cable pulldown.',
  },
  {
    catalogKey: 'close-grip-lat-pulldown',
    name: 'Close Grip Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Neutral or V-bar attachment lat pulldown.',
  },
  {
    catalogKey: 'straight-arm-lat-pulldown',
    name: 'Straight Arm Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Triceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Lat isolation movement keeping arms straight through the arc.',
  },
  {
    catalogKey: 'barbell-bent-over-row',
    name: 'Barbell Bent Over Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Hinged barbell row for overall back thickness and strength.',
  },
  {
    catalogKey: 'pendlay-row',
    name: 'Pendlay Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Strict barbell row pulling from a dead stop on the floor each rep.',
  },
  {
    catalogKey: 'single-arm-dumbbell-row',
    name: 'Single Arm Dumbbell Row',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Upper Back', 'Biceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Bench-supported unilateral dumbbell row.',
  },
  {
    catalogKey: 'chest-supported-dumbbell-row',
    name: 'Chest Supported Dumbbell Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Rear Delts', 'Biceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline bench supported row minimizing lower back fatigue.',
  },
  {
    catalogKey: 't-bar-row',
    name: 'T-Bar Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Close grip landmine or t-bar row for back density.',
  },
  {
    catalogKey: 'seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Horizontal cable row for rhomboids, mid-traps, and lats.',
  },
  {
    catalogKey: 'machine-row',
    name: 'Machine Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Chest-supported seated machine row.',
  },
  {
    catalogKey: 'inverted-row',
    name: 'Inverted Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Abs'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bodyweight horizontal pull under a Smith machine or bar.',
  },

  // LOWER BACK / POSTERIOR CHAIN
  {
    catalogKey: 'conventional-deadlift',
    name: 'Barbell Deadlift',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Upper Back', 'Quads'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 180,
    description: 'Full-body hinge lift pulling from the floor.',
  },
  {
    catalogKey: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Hip hinge focusing on hamstring eccentric stretch.',
  },
  {
    catalogKey: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes', 'Lower Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Dumbbell hip hinge with freedom of hand path.',
  },
  {
    catalogKey: 'back-extension',
    name: 'Back Extension (Hyperextension)',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: '45-degree hyperextension bench extension for erector spinae and glutes.',
  },
  {
    catalogKey: 'good-morning',
    name: 'Good Morning',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Hamstrings', 'Glutes'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Standing barbell hip hinge with bar on upper back.',
  },

  // SHOULDERS (FRONT, SIDE, REAR DELTS)
  {
    catalogKey: 'overhead-press',
    name: 'Overhead Press (OHP)',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Triceps', 'Upper Back', 'Abs'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Standing strict barbell shoulder press.',
  },
  {
    catalogKey: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Side Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Seated vertical dumbbell press for anterior and medial delts.',
  },
  {
    catalogKey: 'arnold-press',
    name: 'Arnold Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Side Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Rotational dumbbell shoulder press popularized by Arnold Schwarzenegger.',
  },
  {
    catalogKey: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Triceps', 'Side Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Guided seated machine overhead press.',
  },
  {
    catalogKey: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing or seated lateral raise targeting medial deltoid width.',
  },
  {
    catalogKey: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Unilateral cable raise providing constant resistance at bottom of range.',
  },
  {
    catalogKey: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated machine lateral raise.',
  },
  {
    catalogKey: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Anterior delt isolation raise.',
  },
  {
    catalogKey: 'rear-delt-dumbbell-fly',
    name: 'Rear Delt Dumbbell Fly',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bent-over reverse dumbbell fly for posterior delts.',
  },
  {
    catalogKey: 'face-pull',
    name: 'Cable Face Pull',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back', 'Side Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'High cable rope pull to eyes/forehead with external shoulder rotation.',
  },
  {
    catalogKey: 'reverse-pec-deck',
    name: 'Reverse Pec Deck (Rear Delt Machine)',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Machine rear delt fly with fixed movement plane.',
  },
  {
    catalogKey: 'barbell-upright-row',
    name: 'Barbell Upright Row',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: ['Upper Back', 'Biceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Upright vertical pull targeting side delts and upper traps.',
  },

];

