import type { CatalogExerciseDefinition } from './gym-exercise-catalog.types';

export const CORE_CONDITIONING_EXERCISES: CatalogExerciseDefinition[] = [
  // ABS / CORE
  {
    catalogKey: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Hanging straight-leg raise for lower abdominals and hip flexors.',
  },
  {
    catalogKey: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Hanging bent-knee tuck for core control.',
  },
  {
    catalogKey: 'cable-woodchopper',
    name: 'Cable Woodchopper',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Diagonal rotational cable pull for obliques and core rotation.',
  },
  {
    catalogKey: 'cable-crunch',
    name: 'Cable Kneeling Crunch',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Kneeling rope crunch allowing weighted progressive resistance for abs.',
  },
  {
    catalogKey: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Lats', 'Shoulders'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Anti-extension core exercise using an ab roller.',
  },
  {
    catalogKey: 'plank',
    name: 'Plank',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Glutes'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Isometric prone forearm plank.',
  },
  {
    catalogKey: 'side-plank',
    name: 'Side Plank',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Isometric lateral core hold for obliques and quadratus lumborum.',
  },

  // CARDIO & CONDITIONING
  {
    catalogKey: 'treadmill-running',
    name: 'Treadmill Running',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Quads', 'Calves', 'Hamstrings'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Running on an indoor motorized treadmill.',
  },
  {
    catalogKey: 'treadmill-incline-walk',
    name: 'Incline Treadmill Walking',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Glutes', 'Calves', 'Hamstrings'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Steep incline walking for low-impact conditioning.',
  },
  {
    catalogKey: 'stationary-bike',
    name: 'Stationary Bike',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Quads', 'Calves'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Upright or spin cycle aerobic conditioning.',
  },
  {
    catalogKey: 'rowing-machine',
    name: 'Rowing Machine (Ergometer)',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Upper Back', 'Lats', 'Quads', 'Biceps'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Full-body cardiovascular rowing.',
  },
  {
    catalogKey: 'stair-climber',
    name: 'Stair Climber',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Glutes', 'Quads', 'Calves'],
    equipment: 'Cardio',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Continuous revolving stair climber machine.',
  },
  {
    catalogKey: 'jump-rope',
    name: 'Jump Rope',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Calves', 'Shoulders', 'Forearms'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Rope skipping for agility, coordination, and aerobic conditioning.',
  },
  {
    catalogKey: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings', 'Lower Back', 'Shoulders', 'Cardio'],
    equipment: 'Kettlebell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Explosive hip hinge swing with a kettlebell.',
  },
  {
    catalogKey: 'burpees',
    name: 'Burpees',
    primaryMuscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Chest', 'Quads', 'Cardio'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Full body calisthenic conditioning movement.',
  },
];

