import type { CatalogExerciseDefinition } from './gym-exercise-catalog.types';

export const ARMS_EXERCISES: CatalogExerciseDefinition[] = [
  // ARMS - BICEPS
  {
    catalogKey: 'barbell-bicep-curl',
    name: 'Barbell Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing straight-bar bicep curl.',
  },
  {
    catalogKey: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cambered bar curl reducing wrist strain.',
  },
  {
    catalogKey: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing or seated alternating dumbbell curl with supination.',
  },
  {
    catalogKey: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Incline bench curl targeting the long head of the bicep under stretch.',
  },
  {
    catalogKey: 'hammer-curl',
    name: 'Dumbbell Hammer Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Neutral grip curl targeting brachialis and brachioradialis.',
  },
  {
    catalogKey: 'preacher-curl',
    name: 'Preacher Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Preacher bench curl isolating the short head of the bicep.',
  },
  {
    catalogKey: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing cable curl with constant tension at peak contraction.',
  },
  {
    catalogKey: 'cable-rope-hammer-curl',
    name: 'Cable Rope Hammer Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Neutral rope cable curl for arm thickness.',
  },
  {
    catalogKey: 'concentration-curl',
    name: 'Concentration Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated single-arm curl against inner thigh.',
  },

  // ARMS - TRICEPS
  {
    catalogKey: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Barbell bench press with shoulder-width grip emphasizing triceps.',
  },
  {
    catalogKey: 'skull-crusher',
    name: 'EZ-Bar Skull Crusher (Lying Tricep Extension)',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Lying tricep extension to forehead or behind head.',
  },
  {
    catalogKey: 'tricep-rope-pushdown',
    name: 'Tricep Rope Pushdown',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cable rope extension spreading ends at lockout.',
  },
  {
    catalogKey: 'straight-bar-tricep-pushdown',
    name: 'Straight Bar Tricep Pushdown',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cable bar pushdown for lateral and medial tricep heads.',
  },
  {
    catalogKey: 'overhead-cable-tricep-extension',
    name: 'Overhead Cable Tricep Extension',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Overhead cable extension loading the long head under deep stretch.',
  },
  {
    catalogKey: 'overhead-dumbbell-tricep-extension',
    name: 'Overhead Dumbbell Tricep Extension',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Two-handed or single-arm overhead dumbbell extension.',
  },
  {
    catalogKey: 'tricep-dip',
    name: 'Tricep Dip (Parallel Bars)',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Upright parallel bar dip emphasizing triceps.',
  },
  {
    catalogKey: 'bench-dip',
    name: 'Bench Dip',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bodyweight dip performed off a flat bench.',
  },

  // FOREARMS
  {
    catalogKey: 'barbell-wrist-curl',
    name: 'Barbell Wrist Curl',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: [],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Seated forearm flexor curl.',
  },
  {
    catalogKey: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Biceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Overhand curl for brachioradialis and wrist extensors.',
  },
  {
    catalogKey: 'farmers-walk',
    name: "Farmer's Walk",
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Upper Back', 'Abs', 'Quads'],
    equipment: 'Dumbbell',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Loaded carry for grip strength and core stability.',
  },
  {
    catalogKey: 'dead-hang',
    name: 'Dead Hang',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Lats', 'Shoulders'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Passive hanging from a pull-up bar for grip endurance and shoulder health.',
  },

];

