import { ExerciseMetricType, WeightUnit } from '../../domain/gym/gym.domain';

export interface CatalogExerciseDefinition {
  catalogKey: string;
  name: string;
  primaryMuscleGroup: string;
  secondaryMuscleGroups: string[];
  equipment: string;
  metricType: ExerciseMetricType;
  defaultWeightUnit: WeightUnit;
  defaultRestSeconds: number;
  description?: string;
}

export const CANONICAL_MUSCLE_GROUPS = [
  'Chest',
  'Back',
  'Lats',
  'Upper Back',
  'Lower Back',
  'Shoulders',
  'Front Delts',
  'Side Delts',
  'Rear Delts',
  'Biceps',
  'Triceps',
  'Forearms',
  'Quads',
  'Hamstrings',
  'Glutes',
  'Calves',
  'Abs',
  'Cardio',
  'Full Body',
] as const;

export const CANONICAL_EQUIPMENT = [
  'Barbell',
  'Dumbbell',
  'Cable',
  'Machine',
  'Bodyweight',
  'Kettlebell',
  'Cardio',
] as const;

export const BUILT_IN_EXERCISE_CATALOG: CatalogExerciseDefinition[] = [
  // CHEST
  {
    catalogKey: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Flat bench barbell press for chest strength and hypertrophy.',
  },
  {
    catalogKey: 'incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Incline bench press targeting clavicular head of the pectoralis.',
  },
  {
    catalogKey: 'decline-barbell-bench-press',
    name: 'Decline Barbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Decline bench press targeting lower pectoral fibers.',
  },
  {
    catalogKey: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Flat dumbbell press allowing deep stretch and independent arm control.',
  },
  {
    catalogKey: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline dumbbell press for upper chest development.',
  },
  {
    catalogKey: 'decline-dumbbell-press',
    name: 'Decline Dumbbell Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Decline dumbbell press emphasizing lower pectorals.',
  },
  {
    catalogKey: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Isolation movement focusing on chest stretch and adduction.',
  },
  {
    catalogKey: 'incline-dumbbell-flyes',
    name: 'Incline Dumbbell Flyes',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Incline flyes for upper chest stretch.',
  },
  {
    catalogKey: 'cable-crossover',
    name: 'Cable Crossover',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing cable chest fly providing constant muscular tension.',
  },
  {
    catalogKey: 'low-to-high-cable-fly',
    name: 'Low to High Cable Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Upward cable fly targeting the upper pectorals.',
  },
  {
    catalogKey: 'high-to-low-cable-fly',
    name: 'High to Low Cable Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Downward cable fly targeting the lower chest.',
  },
  {
    catalogKey: 'chest-dip',
    name: 'Chest Dip',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Parallel bar dips with torso leaned forward to recruit chest.',
  },
  {
    catalogKey: 'push-up',
    name: 'Push Up',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts', 'Abs'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standard floor push up.',
  },
  {
    catalogKey: 'diamond-push-up',
    name: 'Diamond Push Up',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Close hand placement push up targeting triceps and inner chest.',
  },
  {
    catalogKey: 'machine-chest-press',
    name: 'Machine Chest Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Triceps', 'Front Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Guided seated chest press machine.',
  },
  {
    catalogKey: 'incline-machine-chest-press',
    name: 'Incline Machine Chest Press',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts', 'Triceps'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline guided machine press for upper chest.',
  },
  {
    catalogKey: 'pec-deck-fly',
    name: 'Pec Deck Fly',
    primaryMuscleGroup: 'Chest',
    secondaryMuscleGroups: ['Front Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Machine seated chest fly with steady resistance curve.',
  },

  // BACK / LATS / UPPER BACK
  {
    catalogKey: 'pull-up',
    name: 'Pull Up',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Overhand grip pull up for lat width and vertical pulling strength.',
  },
  {
    catalogKey: 'chin-up',
    name: 'Chin Up',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Underhand grip vertical pull with high bicep involvement.',
  },
  {
    catalogKey: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Wide grip seated cable pulldown.',
  },
  {
    catalogKey: 'close-grip-lat-pulldown',
    name: 'Close Grip Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Biceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Neutral or V-bar attachment lat pulldown.',
  },
  {
    catalogKey: 'straight-arm-lat-pulldown',
    name: 'Straight Arm Lat Pulldown',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Triceps', 'Upper Back'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Lat isolation movement keeping arms straight through the arc.',
  },
  {
    catalogKey: 'barbell-bent-over-row',
    name: 'Barbell Bent Over Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Hinged barbell row for overall back thickness and strength.',
  },
  {
    catalogKey: 'pendlay-row',
    name: 'Pendlay Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Strict barbell row pulling from a dead stop on the floor each rep.',
  },
  {
    catalogKey: 'single-arm-dumbbell-row',
    name: 'Single Arm Dumbbell Row',
    primaryMuscleGroup: 'Lats',
    secondaryMuscleGroups: ['Upper Back', 'Biceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Bench-supported unilateral dumbbell row.',
  },
  {
    catalogKey: 'chest-supported-dumbbell-row',
    name: 'Chest Supported Dumbbell Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Rear Delts', 'Biceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Incline bench supported row minimizing lower back fatigue.',
  },
  {
    catalogKey: 't-bar-row',
    name: 'T-Bar Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Close grip landmine or t-bar row for back density.',
  },
  {
    catalogKey: 'seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Horizontal cable row for rhomboids, mid-traps, and lats.',
  },
  {
    catalogKey: 'machine-row',
    name: 'Machine Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Chest-supported seated machine row.',
  },
  {
    catalogKey: 'inverted-row',
    name: 'Inverted Row',
    primaryMuscleGroup: 'Upper Back',
    secondaryMuscleGroups: ['Lats', 'Biceps', 'Abs'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bodyweight horizontal pull under a Smith machine or bar.',
  },

  // LOWER BACK / POSTERIOR CHAIN
  {
    catalogKey: 'conventional-deadlift',
    name: 'Barbell Deadlift',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Upper Back', 'Quads'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 180,
    description: 'Full-body hinge lift pulling from the floor.',
  },
  {
    catalogKey: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Hip hinge focusing on hamstring eccentric stretch.',
  },
  {
    catalogKey: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes', 'Lower Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Dumbbell hip hinge with freedom of hand path.',
  },
  {
    catalogKey: 'back-extension',
    name: 'Back Extension (Hyperextension)',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: '45-degree hyperextension bench extension for erector spinae and glutes.',
  },
  {
    catalogKey: 'good-morning',
    name: 'Good Morning',
    primaryMuscleGroup: 'Lower Back',
    secondaryMuscleGroups: ['Hamstrings', 'Glutes'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Standing barbell hip hinge with bar on upper back.',
  },

  // SHOULDERS (FRONT, SIDE, REAR DELTS)
  {
    catalogKey: 'overhead-press',
    name: 'Overhead Press (OHP)',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Triceps', 'Upper Back', 'Abs'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Standing strict barbell shoulder press.',
  },
  {
    catalogKey: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Side Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Seated vertical dumbbell press for anterior and medial delts.',
  },
  {
    catalogKey: 'arnold-press',
    name: 'Arnold Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Side Delts', 'Triceps'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Rotational dumbbell shoulder press popularized by Arnold Schwarzenegger.',
  },
  {
    catalogKey: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: ['Triceps', 'Side Delts'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Guided seated machine overhead press.',
  },
  {
    catalogKey: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing or seated lateral raise targeting medial deltoid width.',
  },
  {
    catalogKey: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Unilateral cable raise providing constant resistance at bottom of range.',
  },
  {
    catalogKey: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated machine lateral raise.',
  },
  {
    catalogKey: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    primaryMuscleGroup: 'Front Delts',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Anterior delt isolation raise.',
  },
  {
    catalogKey: 'rear-delt-dumbbell-fly',
    name: 'Rear Delt Dumbbell Fly',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bent-over reverse dumbbell fly for posterior delts.',
  },
  {
    catalogKey: 'face-pull',
    name: 'Cable Face Pull',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back', 'Side Delts'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'High cable rope pull to eyes/forehead with external shoulder rotation.',
  },
  {
    catalogKey: 'reverse-pec-deck',
    name: 'Reverse Pec Deck (Rear Delt Machine)',
    primaryMuscleGroup: 'Rear Delts',
    secondaryMuscleGroups: ['Upper Back'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Machine rear delt fly with fixed movement plane.',
  },
  {
    catalogKey: 'barbell-upright-row',
    name: 'Barbell Upright Row',
    primaryMuscleGroup: 'Side Delts',
    secondaryMuscleGroups: ['Upper Back', 'Biceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Upright vertical pull targeting side delts and upper traps.',
  },

  // ARMS - BICEPS
  {
    catalogKey: 'barbell-bicep-curl',
    name: 'Barbell Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing straight-bar bicep curl.',
  },
  {
    catalogKey: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cambered bar curl reducing wrist strain.',
  },
  {
    catalogKey: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing or seated alternating dumbbell curl with supination.',
  },
  {
    catalogKey: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Incline bench curl targeting the long head of the bicep under stretch.',
  },
  {
    catalogKey: 'hammer-curl',
    name: 'Dumbbell Hammer Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Neutral grip curl targeting brachialis and brachioradialis.',
  },
  {
    catalogKey: 'preacher-curl',
    name: 'Preacher Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Preacher bench curl isolating the short head of the bicep.',
  },
  {
    catalogKey: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Standing cable curl with constant tension at peak contraction.',
  },
  {
    catalogKey: 'cable-rope-hammer-curl',
    name: 'Cable Rope Hammer Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Neutral rope cable curl for arm thickness.',
  },
  {
    catalogKey: 'concentration-curl',
    name: 'Concentration Curl',
    primaryMuscleGroup: 'Biceps',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated single-arm curl against inner thigh.',
  },

  // ARMS - TRICEPS
  {
    catalogKey: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Barbell bench press with shoulder-width grip emphasizing triceps.',
  },
  {
    catalogKey: 'skull-crusher',
    name: 'EZ-Bar Skull Crusher (Lying Tricep Extension)',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Lying tricep extension to forehead or behind head.',
  },
  {
    catalogKey: 'tricep-rope-pushdown',
    name: 'Tricep Rope Pushdown',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cable rope extension spreading ends at lockout.',
  },
  {
    catalogKey: 'straight-bar-tricep-pushdown',
    name: 'Straight Bar Tricep Pushdown',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Cable bar pushdown for lateral and medial tricep heads.',
  },
  {
    catalogKey: 'overhead-cable-tricep-extension',
    name: 'Overhead Cable Tricep Extension',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Overhead cable extension loading the long head under deep stretch.',
  },
  {
    catalogKey: 'overhead-dumbbell-tricep-extension',
    name: 'Overhead Dumbbell Tricep Extension',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: [],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Two-handed or single-arm overhead dumbbell extension.',
  },
  {
    catalogKey: 'tricep-dip',
    name: 'Tricep Dip (Parallel Bars)',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Upright parallel bar dip emphasizing triceps.',
  },
  {
    catalogKey: 'bench-dip',
    name: 'Bench Dip',
    primaryMuscleGroup: 'Triceps',
    secondaryMuscleGroups: ['Chest', 'Front Delts'],
    equipment: 'Bodyweight',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Bodyweight dip performed off a flat bench.',
  },

  // FOREARMS
  {
    catalogKey: 'barbell-wrist-curl',
    name: 'Barbell Wrist Curl',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: [],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Seated forearm flexor curl.',
  },
  {
    catalogKey: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Biceps'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Overhand curl for brachioradialis and wrist extensors.',
  },
  {
    catalogKey: 'farmers-walk',
    name: "Farmer's Walk",
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Upper Back', 'Abs', 'Quads'],
    equipment: 'Dumbbell',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Loaded carry for grip strength and core stability.',
  },
  {
    catalogKey: 'dead-hang',
    name: 'Dead Hang',
    primaryMuscleGroup: 'Forearms',
    secondaryMuscleGroups: ['Lats', 'Shoulders'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Passive hanging from a pull-up bar for grip endurance and shoulder health.',
  },

  // LEGS - QUADS
  {
    catalogKey: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Lower Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 150,
    description: 'Foundational lower body compound squat.',
  },
  {
    catalogKey: 'front-squat',
    name: 'Front Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Abs', 'Upper Back'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Anterior-loaded squat with upright torso emphasizing quadriceps.',
  },
  {
    catalogKey: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Abs'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Kettlebell or dumbbell held at chest during squatting.',
  },
  {
    catalogKey: 'leg-press',
    name: 'Leg Press',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Incline machine leg press.',
  },
  {
    catalogKey: 'hack-squat',
    name: 'Hack Squat Machine',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Guided sled squat machine allowing deep knee flexion.',
  },
  {
    catalogKey: 'leg-extension',
    name: 'Leg Extension',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated open-chain quadriceps isolation.',
  },
  {
    catalogKey: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Rear-foot-elevated split squat for unilateral leg power.',
  },
  {
    catalogKey: 'walking-lunge',
    name: 'Walking Lunge',
    primaryMuscleGroup: 'Quads',
    secondaryMuscleGroups: ['Glutes', 'Hamstrings', 'Calves'],
    equipment: 'Dumbbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Dynamic forward lunging with dumbbells or barbell.',
  },

  // LEGS - HAMSTRINGS
  {
    catalogKey: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Calves'],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Prone machine hamstring curl for knee flexion strength.',
  },
  {
    catalogKey: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated hamstring curl loading the hamstrings in a lengthened hip position.',
  },
  {
    catalogKey: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    primaryMuscleGroup: 'Hamstrings',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 90,
    description: 'Eccentric hamstring bodyweight curl.',
  },

  // LEGS - GLUTES
  {
    catalogKey: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings', 'Quads'],
    equipment: 'Barbell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 120,
    description: 'Bench-supported hip thrust for maximal gluteus maximus contraction.',
  },
  {
    catalogKey: 'cable-glute-kickback',
    name: 'Cable Glute Kickback',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Ankle strap cable kickback isolating glutes.',
  },
  {
    catalogKey: 'machine-hip-abduction',
    name: 'Machine Hip Abduction',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Seated machine abduction targeting gluteus medius and minimus.',
  },

  // LEGS - CALVES
  {
    catalogKey: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscleGroup: 'Calves',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Standing straight-leg calf raise targeting gastrocnemius.',
  },
  {
    catalogKey: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    primaryMuscleGroup: 'Calves',
    secondaryMuscleGroups: [],
    equipment: 'Machine',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Bent-knee seated calf raise isolating the soleus muscle.',
  },

  // ABS / CORE
  {
    catalogKey: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Hanging straight-leg raise for lower abdominals and hip flexors.',
  },
  {
    catalogKey: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Forearms'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Hanging bent-knee tuck for core control.',
  },
  {
    catalogKey: 'cable-woodchopper',
    name: 'Cable Woodchopper',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders'],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Diagonal rotational cable pull for obliques and core rotation.',
  },
  {
    catalogKey: 'cable-crunch',
    name: 'Cable Kneeling Crunch',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: [],
    equipment: 'Cable',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Kneeling rope crunch allowing weighted progressive resistance for abs.',
  },
  {
    catalogKey: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Lats', 'Shoulders'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Anti-extension core exercise using an ab roller.',
  },
  {
    catalogKey: 'plank',
    name: 'Plank',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Shoulders', 'Glutes'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Isometric prone forearm plank.',
  },
  {
    catalogKey: 'side-plank',
    name: 'Side Plank',
    primaryMuscleGroup: 'Abs',
    secondaryMuscleGroups: ['Glutes'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 45,
    description: 'Isometric lateral core hold for obliques and quadratus lumborum.',
  },

  // CARDIO & CONDITIONING
  {
    catalogKey: 'treadmill-running',
    name: 'Treadmill Running',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Quads', 'Calves', 'Hamstrings'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Running on an indoor motorized treadmill.',
  },
  {
    catalogKey: 'treadmill-incline-walk',
    name: 'Incline Treadmill Walking',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Glutes', 'Calves', 'Hamstrings'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Steep incline walking for low-impact conditioning.',
  },
  {
    catalogKey: 'stationary-bike',
    name: 'Stationary Bike',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Quads', 'Calves'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Upright or spin cycle aerobic conditioning.',
  },
  {
    catalogKey: 'rowing-machine',
    name: 'Rowing Machine (Ergometer)',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Upper Back', 'Lats', 'Quads', 'Biceps'],
    equipment: 'Cardio',
    metricType: 'DISTANCE_DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Full-body cardiovascular rowing.',
  },
  {
    catalogKey: 'stair-climber',
    name: 'Stair Climber',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Glutes', 'Quads', 'Calves'],
    equipment: 'Cardio',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Continuous revolving stair climber machine.',
  },
  {
    catalogKey: 'jump-rope',
    name: 'Jump Rope',
    primaryMuscleGroup: 'Cardio',
    secondaryMuscleGroups: ['Calves', 'Shoulders', 'Forearms'],
    equipment: 'Bodyweight',
    metricType: 'DURATION',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Rope skipping for agility, coordination, and aerobic conditioning.',
  },
  {
    catalogKey: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    primaryMuscleGroup: 'Glutes',
    secondaryMuscleGroups: ['Hamstrings', 'Lower Back', 'Shoulders', 'Cardio'],
    equipment: 'Kettlebell',
    metricType: 'WEIGHT_REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Explosive hip hinge swing with a kettlebell.',
  },
  {
    catalogKey: 'burpees',
    name: 'Burpees',
    primaryMuscleGroup: 'Full Body',
    secondaryMuscleGroups: ['Chest', 'Quads', 'Cardio'],
    equipment: 'Bodyweight',
    metricType: 'REPS',
    defaultWeightUnit: 'KG',
    defaultRestSeconds: 60,
    description: 'Full body calisthenic conditioning movement.',
  },
];
