import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Trophy } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/ui/card';
import { Skeleton } from '@/shared/ui/skeleton';
import { ChartEmptyState } from './StatisticsSectionStates';
import { GrowthIconMark, growthColorClasses } from '@/shared/ui/GrowthIcons';
import { chartColor, formatNumber, selectTopAttributes } from './statistics';
import type { GrowthSkill, GrowthStatistics } from '@/shared/api/types';

export function StatisticsGrowthSection({ growth, growthOverview }: { growth: { isLoading: boolean; data?: GrowthStatistics }; growthOverview: { isLoading: boolean; data?: { skills?: GrowthSkill[] } } }) {
  const topAttributes = selectTopAttributes(growthOverview.data?.skills ?? []);
  return <section className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]" aria-label="Attribute statistics">
    <Card className="overflow-hidden shadow-[var(--shadow-soft)]"><CardHeader className="border-b bg-muted/20 p-5"><CardTitle className="text-base">Attribute experience distribution</CardTitle><p className="mt-1 text-xs text-muted-foreground">XP earned and lost by attribute inside the selected period.</p></CardHeader><CardContent className="p-5">{growth.isLoading ? <Skeleton className="h-80 w-full" /> : (growth.data?.attributes.length ?? 0) === 0 ? <ChartEmptyState message="Complete rewarded activities to see attribute XP distribution." /> : <><div className="h-64" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><BarChart data={growth.data?.attributes} layout="vertical" margin={{ top: 4, right: 8, bottom: 4, left: 8 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="hsl(var(--border))" /><XAxis type="number" tickLine={false} axisLine={false} fontSize={11} /><YAxis type="category" dataKey="name" tickLine={false} axisLine={false} width={96} fontSize={11} /><Tooltip formatter={(value) => [`${value} XP`, 'Gained']} /><Bar dataKey="gained" radius={[0, 5, 5, 0]}>{growth.data?.attributes.map((attribute) => <Cell key={attribute.skillId} fill={chartColor(attribute.color)} />)}</Bar></BarChart></ResponsiveContainer></div><div className="mt-5 divide-y">{growth.data?.attributes.map((attribute) => <AttributeDistributionRow key={attribute.skillId} attribute={attribute} />)}</div></>}</CardContent></Card>
    <Card className="overflow-hidden shadow-[var(--shadow-soft)]"><CardHeader className="border-b bg-muted/20 p-5"><CardTitle className="flex items-center gap-2 text-base"><Trophy className="h-4 w-4 text-amber-600" aria-hidden="true" />Highest-level attributes</CardTitle><p className="mt-1 text-xs text-muted-foreground">Lifetime ranking with selected-period gains.</p></CardHeader><CardContent className="p-5">{growthOverview.isLoading ? <div className="space-y-3">{Array.from({ length: 5 }, (_, index) => <Skeleton key={index} className="h-16 w-full" />)}</div> : topAttributes.length === 0 ? <ChartEmptyState message="Create an attribute to start tracking levels." /> : <div className="divide-y">{topAttributes.map((attribute, index) => <TopAttributeRow key={attribute.id} attribute={attribute} rank={index + 1} period={growth.data?.attributes.find((item) => item.skillId === attribute.id)} />)}</div>}</CardContent></Card>
  </section>;
}

function AttributeDistributionRow({ attribute }: { attribute: GrowthStatistics['attributes'][number] }) { const colorClass = growthColorClasses[attribute.color] ?? growthColorClasses.TEAL; return <div className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border ${colorClass}`}><GrowthIconMark icon={attribute.icon} className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{attribute.name}</p><p className={`shrink-0 text-sm font-semibold tabular-nums ${attribute.net >= 0 ? 'text-emerald-600' : 'text-destructive'}`}>{attribute.net >= 0 ? '+' : ''}{formatNumber(attribute.net)} XP</p></div><p className="mt-1 text-xs text-muted-foreground"><span className="text-emerald-600">Gained {formatNumber(attribute.gained)}</span>{' · '}<span className={attribute.lost > 0 ? 'text-destructive' : ''}>Lost {formatNumber(attribute.lost)}</span>{' · '}{formatNumber(attribute.changes)} {attribute.changes === 1 ? 'change' : 'changes'}</p></div></div>; }
function TopAttributeRow({ attribute, period, rank }: { attribute: GrowthSkill; period?: GrowthStatistics['attributes'][number]; rank: number }) { const progress = attribute.requiredXp > 0 ? Math.min(100, Math.max(0, (attribute.progressXp / attribute.requiredXp) * 100)) : 0; const colorClass = growthColorClasses[attribute.color] ?? growthColorClasses.TEAL; return <div className="py-4 first:pt-0 last:pb-0"><div className="flex items-center gap-3"><span className="w-5 text-center text-xs font-semibold text-muted-foreground">{rank}</span><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border ${colorClass}`}><GrowthIconMark icon={attribute.icon} className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{attribute.name}</p><p className="shrink-0 text-sm font-semibold">Level {attribute.level}</p></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} role="progressbar" aria-label={`${attribute.name} level progress`} aria-valuemin={0} aria-valuemax={attribute.requiredXp} aria-valuenow={attribute.progressXp} /></div><div className="mt-1.5 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>{formatNumber(attribute.progressXp)} / {formatNumber(attribute.requiredXp)} XP</span><span className="text-emerald-600">+{formatNumber(period?.gained ?? 0)} in range</span></div></div></div></div>; }
