import {
  Activity,
  AlarmClock,
  Apple,
  Archive,
  ArrowUpRight,
  Atom,
  BadgeCheck,
  BadgePlus,
  BarChart3,
  BatteryCharging,
  Bed,
  Bike,
  Book,
  BookCheck,
  BookOpen,
  Bookmark,
  Brain,
  BriefcaseBusiness,
  Brush,
  Calculator,
  CalendarCheck,
  Camera,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  CheckCircle2,
  ChefHat,
  CircleDollarSign,
  ClipboardCheck,
  Clock,
  Code2,
  Coffee,
  Compass,
  CookingPot,
  Crosshair,
  Dumbbell,
  Ear,
  Eye,
  Feather,
  Flame,
  Flower2,
  Focus,
  Footprints,
  Gem,
  Gift,
  Globe,
  Goal,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  HeartHandshake,
  HeartPulse,
  House,
  Image,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Map,
  Medal,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PenLine,
  Pencil,
  Play,
  Puzzle,
  Rocket,
  Route,
  Ruler,
  Scale,
  Scroll,
  Search,
  Shield,
  Smile,
  Sparkles,
  Sprout,
  Star,
  StretchHorizontal,
  Sun,
  Target,
  Timer,
  Trophy,
  Users,
  Utensils,
  WalletCards,
  WandSparkles,
  Waves,
  Weight,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { AuthenticatedImage } from '@/shared/ui/AuthenticatedImage';

export const growthIconOptions = [
  { value: 'SPARKLES', label: 'Sparkles', icon: Sparkles },
  { value: 'ACTIVITY', label: 'Activity', icon: Activity },
  { value: 'ALARM_CLOCK', label: 'Alarm Clock', icon: AlarmClock },
  { value: 'APPLE', label: 'Apple', icon: Apple },
  { value: 'ARCHIVE', label: 'Archive', icon: Archive },
  { value: 'ARROW_UP_RIGHT', label: 'Uptrend', icon: ArrowUpRight },
  { value: 'ATOM', label: 'Science', icon: Atom },
  { value: 'BADGE_CHECK', label: 'Badge Check', icon: BadgeCheck },
  { value: 'BADGE_PLUS', label: 'Badge Plus', icon: BadgePlus },
  { value: 'BAR_CHART_3', label: 'Bars', icon: BarChart3 },
  { value: 'BATTERY_CHARGING', label: 'Energy', icon: BatteryCharging },
  { value: 'BED', label: 'Rest', icon: Bed },
  { value: 'BIKE', label: 'Cycling', icon: Bike },
  { value: 'BOOK', label: 'Book', icon: Book },
  { value: 'BOOK_CHECK', label: 'Study Check', icon: BookCheck },
  { value: 'BOOK_OPEN', label: 'Reading', icon: BookOpen },
  { value: 'BOOKMARK', label: 'Bookmark', icon: Bookmark },
  { value: 'BRAIN', label: 'Brain', icon: Brain },
  { value: 'BRIEFCASE_BUSINESS', label: 'Career', icon: BriefcaseBusiness },
  { value: 'BRUSH', label: 'Brush', icon: Brush },
  { value: 'CALCULATOR', label: 'Math', icon: Calculator },
  { value: 'CALENDAR_CHECK', label: 'Consistency', icon: CalendarCheck },
  { value: 'CAMERA', label: 'Camera', icon: Camera },
  { value: 'CHART_AREA', label: 'Area Chart', icon: ChartArea },
  { value: 'CHART_BAR', label: 'Bar Chart', icon: ChartBar },
  { value: 'CHART_COLUMN', label: 'Column Chart', icon: ChartColumn },
  { value: 'CHART_LINE', label: 'Line Chart', icon: ChartLine },
  { value: 'CHART_NO_AXES_COMBINED', label: 'Growth Chart', icon: ChartNoAxesCombined },
  { value: 'CHECK_CIRCLE_2', label: 'Completed', icon: CheckCircle2 },
  { value: 'CHEF_HAT', label: 'Cooking', icon: ChefHat },
  { value: 'CIRCLE_DOLLAR_SIGN', label: 'Finance', icon: CircleDollarSign },
  { value: 'CLIPBOARD_CHECK', label: 'Checklist', icon: ClipboardCheck },
  { value: 'CLOCK', label: 'Time', icon: Clock },
  { value: 'CODE_2', label: 'Code', icon: Code2 },
  { value: 'COFFEE', label: 'Coffee', icon: Coffee },
  { value: 'COMPASS', label: 'Direction', icon: Compass },
  { value: 'COOKING_POT', label: 'Meal Prep', icon: CookingPot },
  { value: 'CROSSHAIR', label: 'Focus', icon: Crosshair },
  { value: 'DUMBBELL', label: 'Strength', icon: Dumbbell },
  { value: 'EAR', label: 'Listening', icon: Ear },
  { value: 'EYE', label: 'Awareness', icon: Eye },
  { value: 'FEATHER', label: 'Writing', icon: Feather },
  { value: 'FLAME', label: 'Momentum', icon: Flame },
  { value: 'FLOWER_2', label: 'Mindfulness', icon: Flower2 },
  { value: 'FOCUS', label: 'Deep Work', icon: Focus },
  { value: 'FOOTPRINTS', label: 'Steps', icon: Footprints },
  { value: 'GEM', label: 'Value', icon: Gem },
  { value: 'GIFT', label: 'Reward', icon: Gift },
  { value: 'GLOBE', label: 'World', icon: Globe },
  { value: 'GOAL', label: 'Goal', icon: Goal },
  { value: 'GRADUATION_CAP', label: 'Learning', icon: GraduationCap },
  { value: 'HAMMER', label: 'Making', icon: Hammer },
  { value: 'HAND_HEART', label: 'Care', icon: HandHeart },
  { value: 'HEADPHONES', label: 'Audio', icon: Headphones },
  { value: 'HEART_HANDSHAKE', label: 'Relationships', icon: HeartHandshake },
  { value: 'HEART_PULSE', label: 'Health', icon: HeartPulse },
  { value: 'HOUSE', label: 'Home', icon: House },
  { value: 'IMAGE', label: 'Visual', icon: Image },
  { value: 'LANDMARK', label: 'Civics', icon: Landmark },
  { value: 'LANGUAGES', label: 'Languages', icon: Languages },
  { value: 'LAPTOP', label: 'Computer', icon: Laptop },
  { value: 'LEAF', label: 'Nature', icon: Leaf },
  { value: 'LIBRARY', label: 'Library', icon: Library },
  { value: 'LIGHTBULB', label: 'Ideas', icon: Lightbulb },
  { value: 'LIST_CHECKS', label: 'Tasks', icon: ListChecks },
  { value: 'MAP', label: 'Map', icon: Map },
  { value: 'MEDAL', label: 'Medal', icon: Medal },
  { value: 'MESSAGE_CIRCLE', label: 'Communication', icon: MessageCircle },
  { value: 'MIC', label: 'Speaking', icon: Mic },
  { value: 'MICROSCOPE', label: 'Research', icon: Microscope },
  { value: 'MOON', label: 'Sleep', icon: Moon },
  { value: 'MOUNTAIN', label: 'Challenge', icon: Mountain },
  { value: 'MUSIC', label: 'Music', icon: Music },
  { value: 'NOTEBOOK_PEN', label: 'Notes', icon: NotebookPen },
  { value: 'PALETTE', label: 'Art', icon: Palette },
  { value: 'PEN_LINE', label: 'Drafting', icon: PenLine },
  { value: 'PENCIL', label: 'Pencil', icon: Pencil },
  { value: 'PLAY', label: 'Practice', icon: Play },
  { value: 'PUZZLE', label: 'Problem Solving', icon: Puzzle },
  { value: 'ROCKET', label: 'Launch', icon: Rocket },
  { value: 'ROUTE', label: 'Route', icon: Route },
  { value: 'RULER', label: 'Precision', icon: Ruler },
  { value: 'SCALE', label: 'Balance', icon: Scale },
  { value: 'SCROLL', label: 'Knowledge', icon: Scroll },
  { value: 'SEARCH', label: 'Discovery', icon: Search },
  { value: 'SHIELD', label: 'Resilience', icon: Shield },
  { value: 'SMILE', label: 'Mood', icon: Smile },
  { value: 'SPROUT', label: 'Growth', icon: Sprout },
  { value: 'STAR', label: 'Skill', icon: Star },
  { value: 'STRETCH_HORIZONTAL', label: 'Flexibility', icon: StretchHorizontal },
  { value: 'SUN', label: 'Morning', icon: Sun },
  { value: 'TARGET', label: 'Target', icon: Target },
  { value: 'TIMER', label: 'Timer', icon: Timer },
  { value: 'TROPHY', label: 'Trophy', icon: Trophy },
  { value: 'USERS', label: 'People', icon: Users },
  { value: 'UTENSILS', label: 'Food', icon: Utensils },
  { value: 'WALLET_CARDS', label: 'Budget', icon: WalletCards },
  { value: 'WAND_SPARKLES', label: 'Magic', icon: WandSparkles },
  { value: 'WAVES', label: 'Calm', icon: Waves },
  { value: 'WEIGHT', label: 'Training', icon: Weight },
  { value: 'ZAP', label: 'Energy Burst', icon: Zap },
] as const satisfies ReadonlyArray<{ value: string; label: string; icon: LucideIcon }>;

export const growthColorClasses: Record<string, string> = {
  TEAL: 'bg-teal-500/10 text-teal-700 ring-teal-500/20 dark:text-teal-300',
  VIOLET: 'bg-violet-500/10 text-violet-700 ring-violet-500/20 dark:text-violet-300',
  AMBER: 'bg-amber-500/10 text-amber-700 ring-amber-500/20 dark:text-amber-300',
  EMERALD: 'bg-emerald-500/10 text-emerald-700 ring-emerald-500/20 dark:text-emerald-300',
  ROSE: 'bg-rose-500/10 text-rose-700 ring-rose-500/20 dark:text-rose-300',
  BLUE: 'bg-blue-500/10 text-blue-700 ring-blue-500/20 dark:text-blue-300',
  ORANGE: 'bg-orange-500/10 text-orange-700 ring-orange-500/20 dark:text-orange-300',
};

export const growthSolidColorClasses: Record<string, string> = {
  TEAL: 'bg-teal-600 text-white',
  VIOLET: 'bg-violet-600 text-white',
  AMBER: 'bg-amber-600 text-white',
  EMERALD: 'bg-emerald-600 text-white',
  ROSE: 'bg-rose-600 text-white',
  BLUE: 'bg-blue-600 text-white',
  ORANGE: 'bg-orange-600 text-white',
};

function growthIcon(value?: string) {
  return growthIconOptions.find((option) => option.value === value)?.icon ?? Sparkles;
}

export function growthIconLabel(value?: string) {
  return growthIconOptions.find((option) => option.value === value)?.label ?? 'Custom icon';
}

export function isPresetGrowthIcon(value?: string) {
  return growthIconOptions.some((option) => option.value === value);
}

export function isUploadedGrowthIcon(value?: string) {
  return Boolean(value?.startsWith('/media/') || value?.startsWith('http://') || value?.startsWith('https://'));
}

export function GrowthIconMark({ icon, className = 'h-5 w-5' }: { icon: string; className?: string }) {
  if (isUploadedGrowthIcon(icon)) {
    return (
      <AuthenticatedImage
        src={icon}
        alt=""
        className="h-full w-full object-cover"
        fallback={<Sparkles className={className} />}
      />
    );
  }

  const PresetIcon = isPresetGrowthIcon(icon) ? growthIcon(icon) : null;
  if (PresetIcon) return <PresetIcon className={className} />;

  return (
    <span className="max-w-8 truncate text-center text-base font-black leading-none" aria-hidden="true">
      {icon}
    </span>
  );
}
